name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  dart_jsonwebtoken: ^2.12.2
  gcloud: ^0.8.12
  googleapis_auth: ^1.3.1
  image: ^4.1.7
  intl: ^0.19.0
  mysql1: ^0.20.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
